name: Build

on:
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Yarn Setup
      uses: CultureHQ/actions-yarn@v1.0.1

    - name: SPA Build and Publish
      run: |
        yarn --cwd client/Cas-Spa
        yarn --cwd client/Cas-Spa build-linux
        
    - name: .NET Setup
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    
    - name: .NET Restore dependencies
      run: dotnet restore
    
    - name: .NET Build
      run: dotnet build --no-restore
    
    - name: .NET Test
      run: dotnet test --no-build --verbosity normal
