name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Yarn Setup
      uses: CultureHQ/actions-yarn@v1.0.1
    - name: SPA Build and Publish
      run: |
        mkdir publish
        cd client/Cas-Spa
        yarn
        yarn build-linux
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
      
    - name: .NET Publish
      run: |
        dotnet publish -c Release -o publish\gateway --self-contained true gateway\Cas.Gateway\Cas.Gateway.csproj
        dotnet publish -c Release -o publish\customer --self-contained false customer\Cas.Customer.Api\Cas.Customer.Api.csproj
        dotnet publish -c Release -o publish\account --self-contained false account\Cas.Account.Api\Cas.Account.Api.csproj
        dotnet publish -c Release -o publish\transaction --self-contained false transaction\Cas.Transaction.Api\Cas.Transaction.Api.csproj
