name: CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    # only for test!
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Yarn Setup
      uses: CultureHQ/actions-yarn@v1.0.1

    - name: SPA Build and Publish
      run: |
        yarn --cwd \client\Cas-Spa
        yarn --cwd \client\Cas-Spa build-linux
        
    - name: .NET Setup
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    
    - name: .NET Restore dependencies
      run: dotnet restore
    
    - name: .NET Build
      run: dotnet build --no-restore
    
    - name: .NET Test
      run: dotnet test --no-build --verbosity normal
    
    - name: .NET Publish
      run: |
        dotnet publish -c Release -o publish\gateway --self-contained true **\Cas.Gateway.csproj
        dotnet publish -c Release -o publish\client --self-contained false **\Cas.Client.csproj
        dotnet publish -c Release -o publish\customer --self-contained false **\Cas.Customer.Api.csproj
        dotnet publish -c Release -o publish\account --self-contained false **\Cas.Account.Api.csproj
        dotnet publish -c Release -o publish\transaction --self-contained false **\Cas.Transaction.Api.csproj
        